- CHANGELOG.md
- package-lock.json
- package.json
- src/Meta.js
- src/commands/ChangesCommands.js
> Fixed 1.3.14

- CHANGELOG.md
- package-lock.json
- package.json
- src/Meta.js
- src/commands/EnvironmentCommands.js
Hot Fix of Make domain URL configuation when adding a new environment "eu1.make.com" => "eu1.make.com/api"
> Hotfix 1.3.15

- CHANGELOG.md
- package-lock.json
- package.json
- src/Enum.js
- src/Meta.js
- src/commands/ModuleCommands.js
Re-implemented to creating a new universal module
> New Feature

- src/Core.ts
- src/commands/AppCommands.js
- src/commands/ConnectionCommands.js
- src/commands/FunctionCommands.js
- src/commands/ModuleCommands.js
- src/error-handling.ts
Wrapping function `catchError()` introduced. It is not everywhere, but it will be refactorized step-by-step during future development.
> refactor: error handling, code quality

- CHANGELOG.md
- src/commands/AppCommands.js
- src/error-handling.ts
- src/utils.ts
During app import there can be error, or import can fail silently.
This solves also issue #21.
> fix: app import fail

- CHANGELOG.md
- src/Core.ts
- src/commands/AppCommands.js
- src/commands/CoreCommands.js
Now all JSONs are reformated (indent autoformat) on each load or import. It breaks comments and user’s custom indent.
PR removes this feature.
> feat: Keep original JSON indent

- src/commands/FunctionCommands.test.ts
- src/commands/FunctionCommands.ts
Extend the case coverage for IML testing feature
> Extend unit test of IML unit testing

- src/Core.ts
- src/commands/AppCommands.js
- src/commands/ModuleCommands.js
- src/services/module-types-naming.ts
- src/tree/Item.js
- src/types/component-types.types.ts
Purpose: Collect the code about "Module type" into the separate feature service module.
> refactor: module-types-naming

- src/commands/CommonCommands.ts
- src/commands/CoreCommands.ts
- src/commands/FunctionCommands.ts
- src/extension.ts
- src/libs/app-icon.ts
- src/providers/AppsProvider.js
- src/providers/DataProvider.js
- src/providers/GroupsProvider.js
- src/providers/ImlProvider.js
- src/providers/OpensourceProvider.js
- src/providers/RpcProvider.js
- src/providers/StaticImlProvider.js
- src/providers/TempProvider.js
- tsconfig.json
Minor refactor. Very low risk.
> refactor: Remove default exports

- .gitignore
- package.json
- src/Meta.ts
- src/extension.ts
https://integromat.atlassian.net/browse/CDM-9257
> Feat: Publish VSCode context flag `isPreReleaseVersion`

- src/local-development/ask-origin.ts
- src/local-development/deploy.ts
- src/local-development/makecomappjson.ts
Feature:
Quick and dirty solution for adding new origin reference to existing app in Make.
> feat: add new origin

- CHANGELOG.md
- package.json
- src/commands/AccountCommands.js
- src/commands/AppCommands.js
- src/commands/ChangesCommands.js
- src/commands/CoreCommands.ts
- src/commands/EnvironmentCommands.js
- src/libs/app-icon.ts
- src/local-development/code-pull-deploy.ts
- src/local-development/create-remote-component.ts
- src/utils/request-api-make.ts
https://integromat.atlassian.net/browse/CDM-8192
> refactor(api-headers): removed 'x-' prefix from api headers

- README-apps-local-development.md
- package.json
- src/commands/CoreCommands.ts
https://integromat.atlassian.net/browse/CDM-10478
> my apps renamed to custom apps

- CHANGELOG.md
- src/local-development/code-pull-deploy.ts
- src/local-development/deploy.ts
- Improved deployment error messages.
- Error messages from the modal dialog are also placed into the logs terminal now.
> fix: improve deployment error messages

- CHANGELOG.md
- package-lock.json
- package.json
- src/local-development/ask-add-missing-apikey.ts
- src/local-development/ask-origin.ts
- src/local-development/code-pull-deploy.ts
- Added dialogs for selecting/entering the missing origin's API token.
> feat: User flow for adding the missing API token file

- syntaxes/imljson/schemas/response.json
https://integromat.atlassian.net/browse/CDM-11316
> feat(connections): extend connection metadata

- CHANGELOG.md
- src/local-development/create-local-module.ts
- src/local-development/create-local-rpc.ts
- src/local-development/helpers/ask-connection.ts
Change
-------
- Improved wizard of new module: Added questions for connection and alternative connection.
> feat(localdev): ask for connection in new module wizard

- syntaxes/imljson/schemas/parameters.json
Align json schema with:
https://github.com/integromat/imt-web-zone/pull/4603/files
> fix(json-schemas): add min/maxItems into parameters.json

- .gitignore
added: .idea, .fleet
added: .secrets
<code>no-production-impact</code>
> chore: gitignore improvement

- CHANGELOG.md
- src/local-development/align-components-mapping.ts
- src/local-development/ask-mapped-component.ts
- Added "Apply for all" in component mapping alignment process
> feat: add "Apply for all" in component mapping alignment process

- src/local-development/deploy.ts
- src/local-development/helpers/user-preferences.ts
Implemented special dialog for IML Functions access denied error.
> feat: handle IML function "access denied" errors

- CHANGELOG.md
- src/local-development/ask-origin.ts
- src/local-development/helpers/get-origin-object.ts
- Added feature "remember origin and do not ask again".
> feat: "remember origin and do not ask again"

- src/local-development/types/makecomapp.schema.json
Change: Minor change, one sentence improved. No production code changed.
> chore: improve localDeleted description

- .vscodeignore
- CHANGELOG.md
- package-lock.json
- package.json
Change: app package version bump from 2.1.0 to 2.2.0. Fixed changelog. No code change.
> build: app version bump to 2.2.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/local-development/find-code-by-filepath.ts
- src/local-development/makecomappjson.ts
- src/local-development/types/makecomapp.types.ts
- src/utils/typed-object.ts
- syntaxes/local-development/schemas/makecomapp.schema.json
- Fixed the in-editor validation of `makecomapp.json` file.
Internal ticket: https://make.atlassian.net/browse/CDM-8072
> fix: in-editor `makecomapp.json` validation

- CHANGELOG.md
- package.json
- src/local-development/deploy.ts
Change Log
------------
New shortcut for project deployment
*Internal ticket: https://make.atlassian.net/browse/CDM-12351*
> feat: add keyboard shortcut for deployment

- CHANGELOG.md
- Added release day of version 2.2.2. Added minor note to changelog.
> chore: changelog for v 2.2.2

- CHANGELOG.md
- src/extension.ts
CDM-11562
https://make.atlassian.net/browse/CDM-11562
fix issue with deleting local components when their name includes a number.
> fix: fix issue with deleting local components when their name includes a number

- CHANGELOG.md
- package-lock.json
- package.json
Changelog
--------
- Updated release date in changelo
- App version bump from 2.2.2 to 2.2.3
> chore: app version bump to 2.2.3

- CHANGELOG.md
- package-lock.json
- package.json
Changelog
-----------
- version bump from 2.2.3 to 2.2.4
> chore: version 2.2.4 (pre-release)

- CHANGELOG.md
- README-local-development-for-apps.md
- README.md
- package-lock.json
- package.json
- src/local-development/clone.ts
Final release of version 2.2.5. Finalized the changelog also.
> chore: release 2.2.5

- CHANGELOG.md
Change:
doc: update changelog for being compatible with Release Please
No production code changed.
> doc: update changelog for being compatible with Release Please

- action-toolkit.ts
Added action-toolkit.ts configuration used for internal automation processes configuration. No app code changed. Trivial change, so I am skipping PR review.
> chore: add action-toolkit.ts configuration

- actions-toolkit.config.ts
Change Release Please commits types, which triggers the release PR and which are visible in changelog.
No app code change. Trivial change.
> chore(release-please): update hiddenChangeTypesInPublicRepo

- package-lock.json
- package.json
https://make.atlassian.net/browse/CDM-12654
updated @integromat/udt to v1.2.2
updated vulnerable packages with npm audit fix
> fix(dependencies): package.json and package-lock.json updated

- syntaxes/imljson/schemas/parameters.json
CDM-14080
https://make.atlassian.net/browse/CDM-14080
custom apps allow to add description to options
> feat: custom apps allow to add description to options

- src/commands/ModuleCommands.js
https://make.atlassian.net/browse/CDM-14859
> fix: error when creating a new module through the vs code
