CHANGELOG.md, extension.js, package-lock.json, package.json, src/Core.js, src/Meta.js
JSONC formatter is removing all empty lines in documents.
Lib `node-jsonc-parser`, method `format()`. There was similar issue in VS Code, which has been already solved by adding option `keepLines` into this lib.
Upgrade `node-jsonc-parser` and set `keepLines` flag.
Updated extension tested on my local machine in VS Code. Works.
* https://github.com/microsoft/vscode/issues/23260
* https://github.com/microsoft/node-jsonc-parser/pull/66
=> fix(jsonc-parser): do not trim empty lines by JSONC formatter

CHANGELOG.md, src/Enum.js
- Removed unused template "Digest auth".
- Improved changelog sections based on common-changelog.org rules.
=> Remove connection template "Digest auth"

CHANGELOG.md, src/commands/CoreCommands.js, src/error-handling.ts, src/extension.ts, src/temp-dir.ts
Original algoritm made decision if saving file belongs to Make Extension based on if directory path includes "sdk-app" string. But it causes 2 issues:
- Extension uploaded to Make also files, which kept opened in VS Code from previous running.
- Extension tried to upload absolutely every file which has the `sdk-app` in path, even if the file was absolutely irelevant to extension. In this case it generated failing message on each save in VS Code.
Issue 3: Extension kept all temp files on local drive and it neved made cleanup.
Fix: Extension is now deletion own temp dir on each deactivation.
=> fix: Uploading of files not belonging to extension

CHANGELOG.md, src/commands/EnvironmentCommands.js, src/extension.ts
Issue
-----
Extension activation fails if user is activating it on his computer for first time (without extension config stored in VS Code setting.json) + user will cancel the dialog with offer to add new environment. Offer dialog is currently the part of activation function, so it causes failing whole activation process.
Fix
----
- Dialog is executed AFTER the activation - independently on activation function.
Improvement
-------------
- User friendly message if token is invalid.
- User is asked to try again if token is invalid and see the button "Add environment" to be able to simple retry.
=> fix: activation fail on first run

CHANGELOG.md, package-lock.json, package.json, src/Core.ts, src/commands/FunctionCommands.ts, src/extension.ts
Received bug report
===============
There is a longstanding bug within the VSCode extension that prevents the testing of functions utilising other functions written by user   When custom function is using another custom function then test is failing with error
TypeError: iml.<function_name> is not a function . I have quickly investigated the issue and the bug can be easily fixed.What needs to be done:
src -> commands -> FunctionCommands.js
line 104
replace `?cols[]=code` with `?cols[]=name&cols[]=code`
The issue is that it is expected that function object has code and name  properties, in the current implementation the api call returns only code and that leads to the situation when custom functions are not added to the test context. It is a blocker for the Integration Engineering team to …
=> Bug: Custom function testing fails, when using another custom function

.vscode/launch.json, CHANGELOG.md, src/commands/FunctionCommands.test.ts, src/commands/FunctionCommands.ts
Fixing issue:
When tested function was recursive, the unit test started to fail, becuse it was not able to call itself in the custom IML function body.
Other changes:
Minor simplification of testing alghoritm input parameters.
=> fix: recursive IML function unit testing

src/error-handling.ts
Issue:
When API responded error with `detail` and `suberrors` properties together, then `detail` has been ignored and was missing in the final error message
Fix:
Merge `detail` and `suberrors` error messages together in output error message.
=> fix: improve error message handling

CHANGELOG.md, src/local-development/create-remote-component.ts, src/local-development/deploy-metadata.ts
Changes: 
- Fix: `crud` option of action modules was incorrectly defined as mandatory. It is optional in Make.
- Fix: `crud` can be changed anytime in Make, but was in VS Code Extension it has been implemented as persistent before. So reimplemented the deployment of this option, now the value of `crud` option is part of the `Deploy to Make` action.
=> fix: Action module CRUD optional, updatable

src/local-development/create-local-module.ts
Issue: The description is incorrectly marked as optional in the creation wizard. But in Make it is mandatory.
=> fix: make module description mandatory

CHANGELOG.md, src/local-development/create-local-empty-component.ts
change:
- Fix: Action modules have the `crud` as optional only now.
=> fix: action module "crud" as optional

CHANGELOG.md, README-apps-local-development.md, src/local-development/clone.ts, src/local-development/code-pull-deploy.ts, src/local-development/create-local-empty-component.ts, src/local-development/find-code-by-filepath.ts, src/local-development/groups-json.ts, src/local-development/helpers/custom-app-local-project-class.ts, src/local-development/helpers/makecomapp-json-file-class.ts, src/local-development/local-file-paths.ts, src/local-development/pull.ts, src/local-development/types/makecomapp.types.ts
- During the app clone a user chooses to exclude or include the app's common data. If common data are included, they are also committed to GIT.
- Common data files are not being added to `.gitignore` anymore.
=> feat: exclude common data from from local development

CHANGELOG.md, src/local-development/create-local-module.ts, src/local-development/create-remote-component.ts
Change:
Fixes the situation, where was impossible to create a universal module in Make, because of the missing `subtype` property in API.
=> fix: creation of universal module

debug.sh, package.json
VS Extension is runnable/debugable outside of VS scope (WebStorm, shell, ...).
=> feat: ability to debug extension from anywhere

syntaxes/imljson/imljson.tmLanguage
Topic: Spread operator {{...}} breaks syntax-highlight
=> fix(highlighting): fixed highlighting of spread op {{...}}

CHANGELOG.md, package.json, src/extension.ts, src/local-development/align-components-mapping.ts, src/local-development/code-pull-deploy.ts, src/local-development/delete-local-component.ts, src/local-development/delete-origin-component.ts, src/local-development/groups-json.ts, src/local-development/helpers/component-id-mapping-helper.ts, src/local-development/helpers/fs.ts, src/local-development/makecomappjson.ts, src/local-development/pull.ts, src/local-development/types/makecomapp.schema.json, src/local-development/types/makecomapp.types.ts, src/types/app-component-type.types.ts
Implements a right-click context menu and file watcher that automatically removes all associated dependencies when a component is deleted locally. This ensures a clean environment and prevents orphaned dependencies in the project structure.
=> feat: add action to remove component dependencies on deletion

src/local-development/ask-local-dir.ts
Changelog
-------
Fix: `stat()` was addeed, because the `readDirectory()` of non-existing dir generates the weird error `[node.js fs] readdir with filetypes failed with error` in VSCode console, even if the exception is watched.
_Internal ticket: CDM-12187_
=> fix: avoid console error during readDirectory()

CHANGELOG.md, README.md, src/commands/PublicCommands.js, src/providers/ImljsonHoverProvider.js, src/providers/ParametersProvider.ts
Change Log
------------
- Updated URLs to Custom Apps documentation.
Internal ticket: https://make.atlassian.net/browse/CDM-5615
=> fix: update URLs to Custom Apps documentation

CHANGELOG.md, syntaxes/imljson/schemas/parameters.json
Change log:
- Support was added for the theme property of the banner directive in the App Interface.
Internal ticket: https://make.atlassian.net/browse/CDM-12050
=> feat: add support for banner theme into parameters.json

CHANGELOG.md, src/extension.ts
Fixed an issue where components named in camelCase were not being deleted properly due to folders being created in kebab-case format. Adjusted the deletion logic to handle this mismatch correctly.
=> fix: failed to delete a camelcase named module

package.json, src/extension.ts
CDM-12723
https://make.atlassian.net/browse/CDM-12723
key binding for local delete action not working on windows due to wrong path separator.
=> fix: key binding for local delete action not working on windows

package.json
CDM-12724
https://make.atlassian.net/browse/CDM-12724
fix key binding for deploy to work in directory tree panel
=> fix: key binding for deploy to work in directory tree panel

CHANGELOG.md, src/extension.test.ts, syntaxes/imljson/schemas/parameters.json
fix: mappable and static parameters json schema validation issue for plain rpc string
CDM-9321
https://make.atlassian.net/browse/CDM-9321
string is now enabled for parameters
=> fix: mappable and static parameters json schema validation issue for plain rpc string
